### ISSUE TITLE
Attempting to use /api/flags (not /api/flags/${ID}) results in a HTTP 500 Internal Server Error

### ISSUE THREAD

**Issue by Gaming32** [JoeHart/pride-flag-api#17]
## How to recreate the issue
Go to https://pride.dev/api/flags. This is the exact URL referenced on the homepage at https://pride.dev under "Fetch all flags".

**Comment by JoeHart** [comment]
@Gaming32 This should all be fixed now! This was my bad the analytics I was playing around with was breaking the call, it expected to have a global `location` object. So I've just removed that all to let it start working. 

Sorry I only just noticed this issue!
