### ISSUE TITLE
Question about adding flags

### ISSUE THREAD

**Issue by carolstran** [JoeHart/pride-flag-api#3]
Hey there @JoeHart 👋 I love this API and I'd be interested in adding a few more flags to your mix. Quick question before I do though...

Would you prefer that flags be added as individual PRs or could one PR have multiple flags? 

Thank you 🏳️‍🌈 🏳️‍🌈 🏳️‍🌈

**Comment by JoeHart** [comment]
Hey! I'm so glad you want to contribute 🎉. You are the first contributor so we'll very much be figuring out this process together as we go 😅 . I think individual PRs per flag would be best. I'll add this to the Contributing docs for future as well!

**Comment by JoeHart** [comment]
Added some more detail to the docs @carolstran , I will leave the PR up for a bit. Leave any comments on that PR for any bits of the docs that could be better 😄

**Comment by carolstran** [comment]
@JoeHart I'll go through the process of adding a flag tonight and then comment on the PR if I run into anything that could be improved 💃

**Comment by carolstran** [comment]
@JoeHart Added a few comments and suggestions to your PR - feel free to implement any of those that you find relevant (no pressure though). 

Also, the flag I thought was missing totally wasn't 🙈 But I did notice that we have two flags on the [QueerJS](https://queerjs.com/) website that you don't have on the API: [bear](https://en.wikipedia.org/wiki/Bear_flag_(gay_culture)) and [leather](https://en.wikipedia.org/wiki/Leather_Pride_flag). These were added to our website by community members. If you'd be interested in having them on the API, let me know and I'll open a PR 😁
