### ISSUE TITLE
No CORS policy

### ISSUE THREAD

**Issue by muffincode** [JoeHart/pride-flag-api#31]
Hi, I'm trying to use the API for a small front-end project and I get this error message.
Is that on purpose? If not, could you look it up? :) I found [this](https://stackoverflow.com/a/65058898) if it helps

> Access to XMLHttpRequest at 'https://pride.dev/api/flags' from origin 'myurl.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

**Comment by JoeHart** [comment]
@muffincode This should now be fixed and your code should work, let me know if it's not still and I can have a look!
